server:
  port: 8099
  servlet:
    context-path: /analytics
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 800
      # Tomcat?????????????10
      min-spare: 100
spring:
  threads:
    virtual:
      enabled: true
  messages:
    basename: i18n.messages
    encoding: UTF-8
    fallback-to-system-locale: false
    # ????
  servlet:
    multipart:
      # ??????
      max-file-size: 20MB
      # ??????????
      max-request-size: 50MB

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:analytics-sharding-jdbc.yaml
    hikari:
      pool-name: analytics-pool
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-timeout: 4000
      max-lifetime: 60000

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  #???????package?????????
  typeAliasesPackage: com.example.demo.mode.pojo.*
  check-config-location: true
  configuration:
    #?????????????camel case???
    map-underscore-to-camel-case: true
    #????????????????????????????
    cache-enabled: false
    call-setters-on-nulls: true
    #??JdbcTypeForNull, oracle???????
    jdbc-type-for-null: 'null'
    #MyBatis ????????????????? NONE??????? (???), WARNING???????????????, FAILING????????????????????
    auto-mapping-unknown-column-behavior: warning
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      #????  0:"???ID??", 1:"???????",2:"????ID (?????????????????????)", 3:"????ID (idWorker), 4:????ID (UUID), 5:???????ID (idWorker ??????)";
      id-type: AUTO
      #?????? IGNORED:"????", NOT_NULL:"?NULL??", NOT_EMPTY:"????", DEFAULT ???,????????(1. ?????? NOT_NULL,2. ?????? ????)
      field-strategy: NOT_EMPTY
      #??????????
      capital-mode: true
      #?????
      logic-delete-value: 1
      #??????
      logic-not-delete-value: 0